---
name: Release

permissions:
  contents: write

on: push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-release:
    name: Publish Release
    runs-on: macos-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: get_semver
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Create release and tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v$GITVERSION_SEMVER --repo ${{ github.repository }} --generate-notes
          gh release upload v$GITVERSION_SEMVER kinetik-cli--0.13.5.arm64_monterey.bottle.tar.gz --repo ${{ github.repository }}
          gh pkg create --owner ${{ github.actor }} --repo ${{ github.repository }} --tag v$GITVERSION_SEMVER --file kinetik-cli--0.13.5.arm64_monterey.bottle.tar.gz