---
name: Release

permissions:
  contents: write

on: push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-release:
    name: Publish Release
    runs-on: macos-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create release and tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p artifacts
          ls -ll
          gh release create v1.0.0 --repo ${{ github.repository }} --generate-notes
          gh release upload v1.0.0 kinetik-cli--0.13.5.arm64_monterey.bottle.tar.gz --repo ${{ github.repository }}
          mv kinetik-cli--0.13.5.arm64_monterey.bottle.tar.gz artifacts/ # Move the generated bottle files to an artifacts directory

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: artifacts/
#          gh release create v1.0.0 --repo ${{ github.repository }} --generate-notes
#          gh release upload v1.0.0 kinetik-cli.bottle.tar.gz --repo myuser/myrepo